backend:
  name: github
  repo: sergeyyarkov/devthread.ru
media_folder: static/assets
public_folder: /assets
collections:
  - name: "articles"
    label: "Article"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Время чтения", name: "time", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Категория", name: "category", widget: "relation", collection: "categories", valueField: "title", searchFields: ["title"]}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Описание", name: "description", widget: "text"}
      - {label: "Содержание", name: "body", widget: "markdown"}
      - {label: "Тэги", name: "tags", widget: "list"}
  - name: 'categories'
    label: "Category"
    folder: 'content/categories'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Название категории", name: "title", widget: "string"}