backend:
  name: git-gateway
  repo: sergeyyarkov/devthread.ru
locale: 'ru'
media_folder: "static/assets"
public_folder: "/assets"
collections:
  - name: "articles"
    label: "Article"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Время чтения", name: "time", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Популярная статья", name: "popular", widget: "boolean", default: false}
      - {label: "Обложка", name: "image", widget: "image"}
      - {label: "Категория", name: "category", widget: "relation", collection: "categories", valueField: "title", searchFields: ["title"]}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Описание", name: "description", widget: "text"}
      - {label: "Содержание", name: "body", widget: "markdown"}
      - {label: "Тэги", name: "tags", widget: "relation", multiple: true, collection: "tags", valueField: "title", searchFields: ["title"]}
  - name: 'snippets'
    label: "Snippet"
    folder: 'content/snippets'
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Template key", name: "templateKey", widget: "hidden", default: "snippet"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Название сниппета", name: "title", widget: "string"}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Тэги", name: "tags", widget: "list"}
      - {label: "Описание", name: "description", widget: "text"}
      - {label: "Содержание", name: "body", widget: "markdown"}    
  - name: 'categories'
    label: "Category"
    folder: 'content/categories'
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template key", name: "templateKey", widget: "hidden", default: "category"}
      - {label: "Название категории", name: "title", widget: "string"}
  - name: 'tags'
    label: "Tag"
    folder: 'content/tags'
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template key", name: "templateKey", widget: "hidden", default: "tag"}
      - {label: "Название тэга", name: "title", widget: "string"}